### ISSUE TITLE
postinstall in dev env

### ISSUE THREAD

**Issue by Guria** [leonardoanalista/cz-customizable#10]
`postinstall` script in dev environment tries to create config file on 2 levels up. Seems it supposed to be a project root. But in dev environment (`git clone git@github.com:leonardoanalista/cz-customizable.git` + `npm i`) it is not true since current folder is top level project. In my case it tries to write file at `/home/.cz-config.js` and fails.

**Comment by Guria** [comment]
I will investigate it on my own

**Comment by leonardoanalista** [comment]
Yes, it creates a files 2 levels up. The intention is create in the project root.
The initial way I documented was to manually create the file. If there is a better solution post here for discussion. 
cheers
Leonardo

**Comment by Guria** [comment]
I think we could avoid symlink at all. It also have compatibility issues with Windows. Maybe better to use something like https://www.npmjs.com/package/find-config

**Comment by leonardoanalista** [comment]
`find-config` looks good. If we drop the `postinstall` script, it means we need to ask the user to create the file in the root of the project. I am fine about that. 
Locate the file in the home directory (or out of the project) would defy the purpose of this module. The intention is to have scopes specified per projects and file checked in the source repository.

**Comment by Guria** [comment]
It can be solved with options provided to `find-config`

**Comment by Guria** [comment]
Once we will end with #14 I'll try to move onto `find-config` since it would be a breaking change.

**Comment by Guria** [comment]
Seems removing `postinstall` script not so breaking since previous configs would still work.
