### ISSUE TITLE
First character of subject always gets lowercased without upperCaseSubject: true

### ISSUE THREAD

**Issue by taichi-jp** [leonardoanalista/cz-customizable#103]
It is okay that first character gets uppercased with `upperCaseSubject: true` , but I do not want it to always get lowercased without the option.

https://github.com/leonardoanalista/cz-customizable/blob/0ab06f254079cfa37c07ba636e06b1209b907a17/questions.js#L123

I mean, I want it to be something like this.
```js
return (upperCaseSubject ? value.charAt(0).toUpperCase() + value.slice(1) : value); 
```

I think there should be an option like `lowerCaseSubject: boolean` so we can choose whether it gets lowercased or not.

What do you think of it?

**Comment by leonardoanalista** [comment]
There is an option  `upperCaseSubject` and default is false. Just se it to true in your config. Let me know if it works.

**Comment by taichi-jp** [comment]
@leonardoanalista 
Thanks for your replying.
I want the first char not to get uppercased or lowercased. I want it to be as I typed.
If I set `upperCaseSubject: true`, it always get uppercased.

**Comment by taichi-jp** [comment]
I think this is not a bug, but a problem of the specs.

**Comment by leonardoanalista** [comment]
default is false, no matter what you type, it will be lowercase

**Comment by leonardoanalista** [comment]
That's how it's been designed. It needs to be upper or lower case, not up to users in this case.
