### ISSUE TITLE
allow to manually edit resulted commit message

### ISSUE THREAD

**Issue by Guria** [leonardoanalista/cz-customizable#14]
I think we could pass resulted commit message to `git commit -m`

**Comment by leonardoanalista** [comment]
I find sometimes the need to edit some typos in the message. When that happens, I cancel the commit at the last confirmation question, copy the commit and edit. As far as I remember, comittizen passes a function from `gulp-git`. Maybe we can call with params? I will look if we can pass params to `gulp-git` function.

**Comment by Guria** [comment]
I have added a [pr to `commitizen`](https://github.com/commitizen/cz-cli/pull/104) to support passing options to commit.
But seems `gulp-git` doesn't support editor. It displayed but you can not interact with it :(

**Comment by stieben** [comment]
I get an error when trying to edit the message:

```
? Are you sure you want to proceed with the commit above? Edit message
(node:17332) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn vim ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`cz-cli@2.9.6, cz-customizable@5.2.0, yarn@1.3.2`
