### ISSUE TITLE
stop being a fork

### ISSUE THREAD

**Issue by Guria** [leonardoanalista/cz-customizable#18]
There are some issues when project is fork on github:
* forked repositories are not currently searchable
* when creating PR it uses `commitizen/cz-conventional-changelog` as base for merge

**Comment by Guria** [comment]
You can ask github support to make it happen.

**Comment by leonardoanalista** [comment]
cool, thanks for the info. I didn't know that. I submitted a request to git support. Let you know the outcome.

**Comment by leonardoanalista** [comment]
done!

**Comment by Guria** [comment]
Great
