### ISSUE TITLE
lower case first letter of subject field

### ISSUE THREAD

**Issue by leonardoanalista** [leonardoanalista/cz-customizable#2]
Maybe a simple nice to have: 
if `feat('app'): This is a new feature`

change to 

`feat('app'): this is a new feature`

**Comment by Guria** [comment]
vote up

**Comment by Guria** [comment]
can make a pr

**Comment by leonardoanalista** [comment]
Aleksey, 
I think changelog recommends lower case so we could enforce that too.
PR's are always welcome!
cheers
Leonardo

**Comment by kenhowardpdx** [comment]
@leonardoanalista could this be optional, enabled by default? We don't use conventional changelog and my team doesn't want their messages altered.

Example: "docs: aPI documentation", "fix: tHIS BUG WAS CREEPY!"
