### ISSUE TITLE
Question mark prefix is on a different line than the question itself

### ISSUE THREAD

**Issue by beeftornado** [leonardoanalista/cz-customizable#24]
cz-cli displays the '?' and the question on the same line so I assume you intended to keep that behavior. Because your menu config has newlines as the first character, it leaves the '?' on its own line and looks funny.

Otherwise, nice job. I think this project deserves a little more attention because it's definitely helpful.

![screen shot 2016-03-07 at 6 41 03 pm](https://cloud.githubusercontent.com/assets/1356875/13590399/71730e8e-e494-11e5-806e-b6219932f9e8.png)

**Comment by leonardoanalista** [comment]
thank you for reporting. I m gonna fix this shortly.
