### ISSUE TITLE
Support linebreaks in the footer

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/cz-customizable#29]
I mistakenly added a linebreak `|` character in my footer message, which did not get converted into a linebreak. I looked at the code - this shouldn't be too hard to add. The spec (https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit?pref=2&pli=1#heading=h.j8e4paqkfz0q) indicates you can have multiple lines in the footer.

**Comment by stieben** [comment]
I would like to tackle this and have a few questions:

1. Both `breaking` and `footer` should support line breaks with `|`, right?
2. The [2nd gotcha](https://github.com/leonardoanalista/cz-customizable#gotchas) stops being one but the example seems to be a valuable thing to keep in the README. How about a **Usage** section after **Options**?
3. `Use "|" to break new line`: Should this be added to the _breaking_ and _footer_ messages respectively or be part of the info before the 1st question instead?
4. Could you point me to any other file except the following that needs accompanying changes?
  a. `README.md`
  b. `buildCommit.js`
  c. `cz-config-EXAMPLE.js`
  d. `index.js` (maybe)
  e. `questions.js`

**Comment by leonardoanalista** [comment]
@stieben  Sorry for the late reply. Footer should/could behave like message body. If you add `|` to the body, it becomes a breakline. I think this is what this work was about.

**Comment by stieben** [comment]
Thanks for the reply! So I go ahead and open a pull request?
