### ISSUE TITLE
Add option to ask for breaking change as first question

### ISSUE THREAD

**Issue by leonardoanalista** [leonardoanalista/cz-customizable#32]
Rob @rpocklin,

What do you think could be the default answer when option `askForBreakingChangeFirst` is set to true?

If we think that a breaking change is not going to happen very often, a sensible default answer would be in my opinion 'no'. This way, you get the question for breaking changes and if you hit enter, it assumes 'no' and go to next question. Do you think this is a good behaviour? 

Leonardo

**Comment by rpocklin** [comment]
You could go either way.  Make the default configurable!

**Comment by leonardoanalista** [comment]
finally: https://github.com/leonardoanalista/cz-customizable/pull/84
