### ISSUE TITLE
Can you add a License?

### ISSUE THREAD

**Issue by sedayakamercan** [leonardoanalista/cz-customizable#36]
Hello, 

I found this project really useful and hope to use it at my day job. I noticed that you don’t have any open source license in your repo. Any chance you’d consider adding one? MIT or Apache2 would likely be perfect. 

Thanks so much!"

**Comment by leonardoanalista** [comment]
is this enough? @sedayakamercan 

Bty my views are open source projects should always, by default, be the most unrestricted license and there should be no need to mention a license at all. But I add one if most people need for whatever reasons ok.

**Comment by sedayakamercan** [comment]
great thanks so much @leonardoanalista !
