### ISSUE TITLE
Permit refactor/chore/docs to be versionable

### ISSUE THREAD

**Issue by rpocklin** [leonardoanalista/cz-customizable#38]
Currently, adding a `refactor` commit will not allow for a release.  I don't like this behaviour, as it makes the assumption there are no bugs or other benefits in the refactor, which may be true, but you may need or want to bump the version.

This should be customisable so that the user can release a version even though it only has a 'refactor' commit in it.

**Comment by leonardoanalista** [comment]
Hey Rob! how are you man? I am doing a clean up here and closing this issues as it has been moved to https://github.com/leonardoanalista/corp-semantic-release/issues/30
