### ISSUE TITLE
How can you use this adapter alongside another?

### ISSUE THREAD

**Issue by brandondurham** [leonardoanalista/cz-customizable#40]
I’m also using `cz-conventional-changelog`. Is it possible to use both alongside each other? This is my `package.json` config:
```
"config": {
  "commitizen": {
    "path": "cz-conventional-changelog"
  },
  "cz-customizable": {
    "config": "internals/scripts/commitizen/commitizen-customizable.js"
  }
},
```

**Comment by brandondurham** [comment]
I now realize `cz-customizable` consumes the functionality of `cz-conventional-changelog`, but I suppose the question still stands.

**Comment by leonardoanalista** [comment]
We have no plans to support this feature. The reason this project exists is because `cz-conventional-changelog` fell short in customisation. This project was forked from cz-conventional-changelog in yearly days.

**Comment by brandondurham** [comment]
I’m sorry man, but I find that unacceptable. I hear it from so many different repos and for me it just comes across as nothing but languid.

I suppose this means if I want it I make _yet another_ forked repo. Onward and upward.

**Comment by leonardoanalista** [comment]
Fair enough. Do you have a good use case for supporting multiple commitizen adaptors on the same project? Remember cz-customizable is triggered by commitizen. Maybe come with a use case for your feature.

**Comment by brandondurham** [comment]
I’m thinking that might come served best as a small repo?
