### ISSUE TITLE
I think the newer version of conventional-changelog has changed the footerPrefix

### ISSUE THREAD

**Issue by uglow** [leonardoanalista/cz-customizable#44]
Hi @leonardoanalista , I've noticed that for a commit like this:
```
fix(radar): reimplement add blip function while in RFC mode

ISSUES CLOSED: #RAD-658
```
... the latest version of `corp-semantic-release` does **not** create a link in the changelog (when using `conventional-changelog-angular-bitbucket`, and I suspect, other presets)

If you see [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core/hosts), the keywords for detecting issues do not include 'ISSUES CLOSED:'.  

After amending the commit to:
```
fix(radar): reimplement add blip function while in RFC mode

Closes #RAD-658
```
... I get the correct(?) output in the changelog:
```
* **radar:** reimplement add blip function while in RFC mode ([ab8fed2](https://repo.com.au/projects/in/repos/repo-name/commits/ab8fed2)), closes [#RAD-658](https://www.atlassian.net/browse/RAD-658)
```

**Comment by leonardoanalista** [comment]
We now support `footerPrefix` configuration. Default is `'ISSUES CLOSED:'`
