### ISSUE TITLE
Add option to set specific questions as required

### ISSUE THREAD

**Issue by kenhowardpdx** [leonardoanalista/cz-customizable#45]
Currently the `type` and `subject` are the only questions that require any input. I'd like to configure `scope` as a required field and maybe conditionally require `footer` when `scope === 'feat'`.

**Comment by leonardoanalista** [comment]
Hi Ken,

Just fyi, it is not only type and subject that allow input. Scope allows input if you select `custom`. Please refer to screen shots on main project page.

Conditionally require a field depending on another field sounds like a good feature. 

regards
Leonardo
