### ISSUE TITLE
Scope shouldn't be prompted when `scopeOverrides` is defined as an empty array

### ISSUE THREAD

**Issue by sveinburne** [leonardoanalista/cz-customizable#47]
``` javascript
module.exports = {
  scopeOverrides: {
    chore: []
  }
}
```
This setting shouldn't prompt user for a scope, but it does 
![image](https://user-images.githubusercontent.com/3646758/31509249-df70f992-af4e-11e7-84db-befe1abd3ca8.png)

**Comment by leonardoanalista** [comment]
Thanks for reporting. Does it prompt scope if you remove the array? 
The code might be checking if variable is set.

**Comment by sveinburne** [comment]
The [code responsible for this behaviour is here](https://github.com/leonardoanalista/cz-customizable/blob/2a3752a117b322301c4f00d9db5ed635d840337a/questions.js#L64). I guess "no scope" means "custom scope" for you ; that's an understandable behaviour.

**Comment by leonardoanalista** [comment]
Hi Jules, if config prop `allowCustomScopes` is set, you'll be able to type a scope which may not be present in the pre-defined list. It is useful when you are working out new scopes in a middle of a commit. 
For an empty scope, just hit `enter` and it should jump to the next question. See here the code to build message if scope exists: https://github.com/leonardoanalista/cz-customizable/blob/master/buildCommit.js#L18
