### ISSUE TITLE
Feature request: Generate config from git history

### ISSUE THREAD

**Issue by goodmind** [leonardoanalista/cz-customizable#48]
I would want to parse scopes from git history and write them to config. Is this possible?

**Comment by leonardoanalista** [comment]
It is possible. Basically loop over all parsed commits and detect supported features to create the confit file.

**Comment by leonardoanalista** [comment]
This would be a great tool to have. However, config should has sensible defaults which works for most people. I am closing this for now as it is not priority at the moment.
