### ISSUE TITLE
Custom order of messages in commit

### ISSUE THREAD

**Issue by bm-stschneider** [leonardoanalista/cz-customizable#49]
Is there a way to change the order of how the messages are put into the commit message?
For example if I want the appendBranchNameToCommitMessage right in the first line?

**Comment by leonardoanalista** [comment]
it hasn't been implemented. As per this file `https://github.com/leonardoanalista/cz-customizable/blob/master/questions.js#L29`, array is statically defined. I think it would be hard to implement this feature. Look fields `when` and how some answers depend on others.

**Comment by leonardoanalista** [comment]
Commit message append is done by this other associated package:
https://github.com/uglow/cz-customizable-ghooks/blob/master/lib/index.js#L232
As con can see, it would be necessary a new option to `prependBranchName...`.

**Comment by bm-stschneider** [comment]
At minimum, better would be maybe a function with a fixed amount of arguments that would generate the commit message so someone could restructure the commit message by changing the order.

**Comment by leonardoanalista** [comment]
It's one way of doing. I'd suggest to open this issue on `cz-customizable-ghooks` repo and see what Brett thinks about it. He may have further alternatives to handle your case.

**Comment by leonardoanalista** [comment]
it sounds like a good idea

**Comment by leonardoanalista** [comment]
I am not sure if this is still needed. We can reopen the discussion at any stage.
