### ISSUE TITLE
allow breaking changes only for feat

### ISSUE THREAD

**Issue by leonardoanalista** [leonardoanalista/cz-customizable#5]
This up for a discussion so your opinion is important:

As we know, semantic-release will detect the word `BREAKING CHANGE` and bump version to major.

Maybe cz-customizable should not allow the words `BREAKING CHANGE` on footer if commit type is for example `refactor` or `docs`. 

I think word `closes` should be allowed but not `BREAKING CHANGE`. 

What do you guys think?

**Comment by Guria** [comment]
what about anomaticly add words "BREAKING CHANGE:" whan they provided like in https://github.com/rebelliard/rb-conventional-changelog ?

**Comment by leonardoanalista** [comment]
a feature is not necessarily a breaking change. I am not sure exactly what you mean. Do you have an example?

**Comment by Guria** [comment]
I mean it should be separate question for breaking changes which will add "BREAKING CHANGE:" section. So you could limit for which commit types to ask this question.
