### ISSUE TITLE
Feature request: Ask for ticket-number

### ISSUE THREAD

**Issue by smollweide** [leonardoanalista/cz-customizable#50]
In many projects jira or something similar is used.
It would be great to ask the user for the ticket number.
The result could be: `fix(scope): Ticket-1234 subject`

Thanks for this project 👍

**Comment by brandondurham** [comment]
Will there be any documentation added to the README? How do you add the config item?

**Comment by leonardoanalista** [comment]
Sorry I missed that in the code review. I created ticket: https://github.com/leonardoanalista/cz-customizable/issues/72
