### ISSUE TITLE
Add Typescript Support

### ISSUE THREAD

**Issue by trodi** [leonardoanalista/cz-customizable#57]
I recently used `cz-customizable` in a Typescript project. Instead of writing the config in javascript, I opted to write it in [Typescript](https://www.typescriptlang.org/). I wrote the corresponding definition typings file to get type safety. Ideally these files live with and thus synced with their project, therefore I'd like to make a pull request to add them to `cz-customizable`. If your config object changed going forward, we'd update these typing at the same time.

Changes would include:
- `typings` property added to the package.json
- new `d.ts` file at root

If this is outside the scope of your project, I'll add them to the official typings repo: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). This would just require consumers to add an additional dependency when consuming `cz-customizable` with Typescript.

**Comment by leonardoanalista** [comment]
it sounds good to me to.
