### ISSUE TITLE
Double backticks escaping is no longer required

### ISSUE THREAD

**Issue by RomanMinkin** [leonardoanalista/cz-customizable#67]
Double backticks escaping was introduced in https://github.com/leonardoanalista/cz-customizable/commit/99aa05b3dcac9113ebc98d97e813104342e2db7e to fix #23 , but it's no longer required since `commitizen@2.7.6` has fix it https://github.com/commitizen/cz-cli/pull/173/commits/5f7737f599ae4123580c855708319b56e2fee17f

Current code produces extra escaping for non `win32` architectures:
```
feat(auth): CLOUD-1058 some \`stuff\`
```

Do you guys want me to open up a PR?

**Comment by axiac** [comment]
This issue is present again in version `6.2.0`.
I cannot tell about the previous `6.x` versions.
