### ISSUE TITLE
From v5.5.1, dependency "winston" was updated upto v3, which leads to a problem 

### ISSUE THREAD

**Issue by StinsonZhao** [leonardoanalista/cz-customizable#69]
From v5.5.1, dependency "winston" was updated upto v3(before is v2), which leads to incorrect log:

![image](https://user-images.githubusercontent.com/6703905/54340596-afbb1400-4672-11e9-9378-a50062cdb135.png)

**Comment by leonardoanalista** [comment]
Hi @StinsonZhao,  Thanks for reporting, I am working on it now 👍
