### ISSUE TITLE
Add possibility to skip footer prefix

### ISSUE THREAD

**Issue by rylek90** [leonardoanalista/cz-customizable#73]
Currently there's no option to skip `{ footerPrefix }` by setting it to empty string.

Sometimes commit only references (or partially fixes) specific issues without need to automatically close them as described in https://help.github.com/en/articles/closing-issues-using-keywords

Acceptance criteria:
Configuration should accept `{ footerPrefix: '' }` or `{ skipFooterPrefix: true }` and produce commit with following footer:
```
whatever developer typed here 
```

**Comment by leonardoanalista** [comment]
it sounds good to me. Thank you!
