### ISSUE TITLE
there is different way between `npx git-cz` and `git cz`

### ISSUE THREAD

**Issue by xxholly32** [leonardoanalista/cz-customizable#78]
system：
win 10,
npm 6
node 10

it has emoji in `npx git-cz`

![image](https://user-images.githubusercontent.com/6063358/55528690-558cfc00-56d0-11e9-8011-a7bbe780d78c.png)

`git-cz` 

![image](https://user-images.githubusercontent.com/6063358/55528706-69d0f900-56d0-11e9-81c5-88bcc5cafb4c.png)

why git-cz cant have emoji?

**Comment by leonardoanalista** [comment]
Ia m not sure. I'll need to investigate....
what's your `cz-customizable` version?

**Comment by xxholly32** [comment]
actually i just use cz-cli , i think my question was in wrong place, ty
