### ISSUE TITLE
Add allowEmptyScope to configuration

### ISSUE THREAD

**Issue by rylek90** [leonardoanalista/cz-customizable#81]
Since, there's a rule scope-empty here https://conventional-changelog.github.io/commitlint/#/reference-rules?id=scope-empty

For people using `cz-customizable` along with `commitlint` it'd be nice to have possibility to enforce scope.

AC:
* Add `{ allowEmptyScope }` with default `true` to configuration.
* When `allowEmptyScope === false` don't make it possible to skip this question while commiting

I can push a PR for this soon if no one will pick this.

**Comment by leonardoanalista** [comment]
It sounds good to me. 
I was going to write a PR today to skip scope. Some places we just want to commit like “feat: this is my feature”. In those cases, scope is unimportant and better if the question is not even asked. Maybe this is a different case.

Btw I think we have an option to allow empty scope already. Let me have a look later. I’m in the phone now.

**Comment by leonardoanalista** [comment]
I think scope can be empty, or even “custom” for you to type. Take a look at the code before you write a PR for this. Cheers Leo

**Comment by rylek90** [comment]
@leonardoanalista thanks, I'll do a double-check. Guess this one can wait since at our side we do linting later 🤔

**Comment by leonardoanalista** [comment]
we have this outcome when `allowCustomScopes = true`

![image](https://user-images.githubusercontent.com/501420/55692197-f6d5c400-59e8-11e9-8c0a-ed99de5452dd.png)

It allows you to select, manually type of have it empty. 

Currently, if you don't have `scope` array in your config, it will allow you to type the scope. I think this is useful to most users - question is always asked as per today.

We can create a new option `skipScope` to not ask the scope question at all. This would take precedence over `scope` array in config file and `allowCustomScopes`. This is actually my case where I work. We never use scope but always have a commit type e.g. `[minor] this is a new feature`.

I can implement this soon as you have a way around this issue for now.

**Comment by leonardoanalista** [comment]
Actually we have already the option `skipQuestions`, type array of string for this purpose. So 
`skipQuestions: ['scope']` would not ask `scope` question at all.
