### ISSUE TITLE
Add possibility to leave subject capitilized

### ISSUE THREAD

**Issue by rylek90** [leonardoanalista/cz-customizable#82]
Since, there's a rule https://conventional-changelog.github.io/commitlint/#/reference-rules?id=subject-case to enforce subject's case.

For people using `cz-customizable` along with `commitlint` it'd be nice to have possibility to leave subject as is (do not make it lowercase).

AC:
* Add `{ lowerCaseSubject }` with default `true` to configuration.
* When `loweCaseSubject === false` do not transform subject from `This is subject` to `this is subject`

I can push a PR for this soon if no one will pick this.

**Comment by leonardoanalista** [comment]
I like it! Default value sounds good, no breaking changes. 
Feel free to decide between “upperCaseSubject” with default false or your suggestion
